### ISSUE TITLE
Fails on Windows 

### ISSUE THREAD

**Issue by reeshabhranjan** [RuchiTanmay/nselib#19]
```Traceback (most recent call last):
  File "<redacted-path>\.venv\Lib\site-packages\nselib\capital_market\capital_market_data.py", line 96, in get_price_volume_data
    f.write(data_text)
  File "C:\Users\reesh\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\x82' in position 178: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<redacted-path>\ml\clean_cointegration.py", line 102, in <module>
    stock_data1 = fetch_stock_data(stock_symbol1, start_date, end_date)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<redacted-path>\ml\clean_cointegration.py", line 22, in fetch_stock_data
    df = capital_market.price_volume_data(symbol=symbol, from_date=start_date, to_date=end_date)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<redacted-path>\.venv\Lib\site-packages\nselib\capital_market\capital_market_data.py", line 83, in price_volume_data
    data_df = get_price_volume_data(symbol=symbol, from_date=start_date, to_date=end_date)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<redacted-path>\.venv\Lib\site-packages\nselib\capital_market\capital_market_data.py", line 99, in get_price_volume_data
    raise NSEdataNotFound(f" Resource not available MSG: {e}")
nselib.libutil.NSEdataNotFound:  Resource not available MSG: 'charmap' codec can't encode character '\x82' in position 178: character maps to <undefined>
```

**Comment by RuchiTanmay** [comment]
Hi, Please Try with new version nselib 1.0
pip install nselib --upgrade
